name: CapCut Farm Final
on: workflow_dispatch

jobs:
  run-android:
    runs-on: ubuntu-latest
    steps:
      - name: Start Android Emulator (Budtmo)
        run: |
          # অ্যান্ড্রয়েড ৯.০ ইমেজে এটি সবচেয়ে হালকা এবং ফাস্ট চলবে
          sudo docker run -d -p 6080:6080 \
            -e EMULATOR_DEVICE="Samsung Galaxy S10" \
            -e WEB_VNC=true \
            --name android-container \
            budtmo/docker-android-x86-9.0
          echo "Emulator is starting, please wait..."

      - name: Setup Connection
        run: |
          # ক্লাউডফ্লেয়ার ইনস্টল
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          
          echo "------------------------------------------"
          echo "আপনার ফোন স্ক্রিন লিঙ্কটি নিচে তৈরি হচ্ছে..."
          echo "লিঙ্কটি আসার পর ব্রাউজারে ওপেন করুন।"
          echo "------------------------------------------"
          
          # টানেল রান করা (পোর্ট ৬০৮০ তে VNC স্ক্রিন থাকে)
          sudo cloudflared tunnel --url http://localhost:6080
